### ISSUE TITLE
Lua 5.3.6 overriding dependencies gone wrong

### ISSUE THREAD

**Issue by averms** [mesonbuild/lua#13]
Hm I think I messed something up around overriding dependencies in the wrap file. I'm getting the following error when I try to test it:

```
meson.build:44:0: ERROR: Subproject subprojects/lua did not override dependency lua
```

**Comment by eli-schwartz** [comment]
In #12 you added a "[provides]" section instead of "[provide]".

@jpakkane

**Comment by averms** [comment]
~~Changing that in my local `lua.wrap` doesn't seem to fix it. Does it work for you?~~

EDIT: nvm that was a mistake on my end.

**Comment by eli-schwartz** [comment]
Keep in mind you're providing the dependency `lua-5.3` not `lua`, and there's so many incoherent ways for the Lua project to not communicate their expectations to downstream consumers that the homebrew library provided by various vendors might be "lua-5.3.so", "lua5.3.so", "lua53.so", "lua-53.so", or plain old "lua.so". And the dependency() might be "lua-5.3", "lua5.3", "lua53", "lua-53", or plain old "lua". And sometimes, the library name and the dependency name are different variants.

This is the curse of an indecisive upstream that thinks it's a "good" thing and "is beneficial to users" to "make the name of the library configurable". They refuse to provide pkg-config files because they think pkg-config files are used by dictators whose jack-booted heels of oppression are forcing you to use a specific name.

So a large part of knowing how to use lua is figuring out what it is called. In the case of this wrap, it's called exactly what you put in `[provide]`: "lua-5.3"
